const LOGIN_USER = "LOGIN_USER";
const LOGOUT_USER = "LOGOUT_USER";
const FILTER_EVENT_ITEMS = "FILTER_EVENT_ITEMS";
const RECORD_ERROR = "RECORD_ERROR";
const CLEAR_ERROR = "CLEAR_ERROR";

module.exports = {
    LOGIN_USER,
    LOGOUT_USER,
    FILTER_EVENT_ITEMS,
    RECORD_ERROR,
    CLEAR_ERROR
};